spring:
  profiles:
    active:
    - prod
  application:
    name: "accounts"
  config:
    import: "optional:configserver:http://localhost:8070"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"  
    password: "guest"  
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
 

