server:
 port: 8900
spring:
  config:
    import: "optional:configserver:http://localhost:8901"
  application:
    name: eurekaserver


management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true